export const personList = [
  {
    id: 1,
    firstName: "Filberto",
    lastName: "Snailham",
    userPhoto: "http://dummyimage.com/138x100.png/ff4444/ffffff",
    userMail: "fsnailham0@weather.com",
    userGender: "Polygender",
  },
  {
    id: 2,
    firstName: "Cris",
    lastName: "McLleese",
    userPhoto: "http://dummyimage.com/104x100.png/5fa2dd/ffffff",
    userMail: "cmclleese1@geocities.com",
    userGender: "Male",
  },
  {
    id: 3,
    firstName: "Clair",
    lastName: "Klemke",
    userPhoto: "http://dummyimage.com/205x100.png/dddddd/000000",
    userMail: "cklemke2@diigo.com",
    userGender: "Male",
  },
  {
    id: 4,
    firstName: "Lianna",
    lastName: "Edmons",
    userPhoto: "http://dummyimage.com/101x100.png/5fa2dd/ffffff",
    userMail: "ledmons3@psu.edu",
    userGender: "Female",
  },
  {
    id: 5,
    firstName: "Abbi",
    lastName: "Karlolczak",
    userPhoto: "http://dummyimage.com/232x100.png/ff4444/ffffff",
    userMail: "akarlolczak4@state.gov",
    userGender: "Female",
  },
  {
    id: 6,
    firstName: "Carmelina",
    lastName: "Harfleet",
    userPhoto: "http://dummyimage.com/236x100.png/cc0000/ffffff",
    userMail: "charfleet5@woothemes.com",
    userGender: "Female",
  },
  {
    id: 7,
    firstName: "Dulcie",
    lastName: "Orable",
    userPhoto: "http://dummyimage.com/201x100.png/cc0000/ffffff",
    userMail: "dorable6@reverbnation.com",
    userGender: "Female",
  },
  {
    id: 8,
    firstName: "Brigit",
    lastName: "Longworth",
    userPhoto: "http://dummyimage.com/233x100.png/dddddd/000000",
    userMail: "blongworth7@state.tx.us",
    userGender: "Female",
  },
  {
    id: 9,
    firstName: "Royall",
    lastName: "Baglin",
    userPhoto: "http://dummyimage.com/240x100.png/dddddd/000000",
    userMail: "rbaglin8@reverbnation.com",
    userGender: "Male",
  },
  {
    id: 10,
    firstName: "Eula",
    lastName: "Icom",
    userPhoto: "http://dummyimage.com/157x100.png/ff4444/ffffff",
    userMail: "eicom9@naver.com",
    userGender: "Female",
  },
  {
    id: 11,
    firstName: "Almira",
    lastName: "Huckell",
    userPhoto: "http://dummyimage.com/200x100.png/cc0000/ffffff",
    userMail: "ahuckella@amazonaws.com",
    userGender: "Female",
  },
  {
    id: 12,
    firstName: "Tricia",
    lastName: "Simone",
    userPhoto: "http://dummyimage.com/239x100.png/dddddd/000000",
    userMail: "tsimoneb@zdnet.com",
    userGender: "Female",
  },
  {
    id: 13,
    firstName: "Jude",
    lastName: "Roisen",
    userPhoto: "http://dummyimage.com/183x100.png/ff4444/ffffff",
    userMail: "jroisenc@theatlantic.com",
    userGender: "Male",
  },
  {
    id: 14,
    firstName: "Marney",
    lastName: "Mateuszczyk",
    userPhoto: "http://dummyimage.com/213x100.png/ff4444/ffffff",
    userMail: "mmateuszczykd@youku.com",
    userGender: "Female",
  },
  {
    id: 15,
    firstName: "Rozella",
    lastName: "Seabon",
    userPhoto: "http://dummyimage.com/101x100.png/5fa2dd/ffffff",
    userMail: "rseabone@tiny.cc",
    userGender: "Female",
  },
];
